version: '3'

services: 
  web:
    build: .
    ports: 
      - '3000:3000'
      - '4000:4000' # capybara port
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
    depends_on:
      - selenium_chrome
  
  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    
  redis:
    image: redis
 
  database:
    image: postgres
    volumes: 
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env/development/database
  
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports: 
      - "5900:5900"

volumes:
  db_data:
